### PR TITLE
May not be needed, but as is launchy does not compile.

### PR DESCRIPTION
**Pull request by rbreaves**
I've made a few commits trying to get it in a state where it does compile but I have not been successful.

The output I get. Also I have been able to compile panther launcher just fine.

$ make
[  2%] Generating /home/ryanr/fork-launchy/build/src/Config.c;Backend/App.c;Backend/AppSystem.c;Backend/DBusService.c;Backend/SynapseSearch.c;Launchy.c;LaunchyView.c;Pixels.c;Settings.c;Utils.c;Widgets/AppEntry.c;Widgets/CategoryView.c;Widgets/Grid.c;Widgets/SearchItem.c;Widgets/SearchView.c;Widgets/StaredView.c;Widgets/Sidebar.c;Widgets/Switcher.c;synapse-core/common-actions.c;synapse-core/config-service.c;synapse-core/data-sink.c;synapse-core/dbus-service.c;synapse-core/desktop-file-service.c;synapse-core/match.c;synapse-core/plugin.c;synapse-core/query.c;synapse-core/relevancy-backend-zg.c;synapse-core/relevancy-service.c;synapse-core/result-set.c;synapse-core/utils.c;synapse-core/volume-service.c;synapse-plugins/calculator-plugin.c;synapse-plugins/command-plugin.c;synapse-plugins/desktop-file-plugin.c;synapse-plugins/system-managment.c
/home/ryanr/fork-launchy/src/synapse-core/desktop-file-service.vala:76.5-76.37: warning: the modifier `static' is not applicable to constants
    private static const string GROUP = "Desktop Entry";
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
/home/ryanr/fork-launchy/src/synapse-core/dbus-service.vala:29.5-29.53: warning: DBus methods are recommended to throw at least `GLib.Error' or `GLib.DBusError, GLib.IOError'
    public abstract async string[] list_queued_owners (string name) throws IOError;
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
/home/ryanr/fork-launchy/src/synapse-core/dbus-service.vala:30.5-30.45: warning: DBus methods are recommended to throw at least `GLib.Error' or `GLib.DBusError, GLib.IOError'
    public abstract async string[] list_names () throws IOError;
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
/home/ryanr/fork-launchy/src/synapse-core/dbus-service.vala:31.5-31.57: warning: DBus methods are recommended to throw at least `GLib.Error' or `GLib.DBusError, GLib.IOError'
    public abstract async string[] list_activatable_names () throws IOError;
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
/home/ryanr/fork-launchy/src/synapse-core/dbus-service.vala:32.5-32.45: warning: DBus methods are recommended to throw at least `GLib.Error' or `GLib.DBusError, GLib.IOError'
    public abstract async bool name_has_owner (string name) throws IOError;
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
/home/ryanr/fork-launchy/src/synapse-core/dbus-service.vala:36.5-36.54: warning: DBus methods are recommended to throw at least `GLib.Error' or `GLib.DBusError, GLib.IOError'
    public abstract async uint32 start_service_by_name (string name,
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
/home/ryanr/fork-launchy/src/synapse-core/dbus-service.vala:38.5-38.47: warning: DBus methods are recommended to throw at least `GLib.Error' or `GLib.DBusError, GLib.IOError'
    public abstract async string get_name_owner (string name) throws IOError;
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
/home/ryanr/fork-launchy/src/synapse-plugins/system-managment.vala:56.5-56.31: warning: DBus methods are recommended to throw at least `GLib.Error' or `GLib.DBusError, GLib.IOError'
    public abstract void reboot (bool interactive) throws IOError;
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
/home/ryanr/fork-launchy/src/synapse-plugins/system-managment.vala:57.5-57.32: warning: DBus methods are recommended to throw at least `GLib.Error' or `GLib.DBusError, GLib.IOError'
    public abstract void suspend (bool interactive) throws IOError;
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
/home/ryanr/fork-launchy/src/synapse-plugins/system-managment.vala:58.5-58.34: warning: DBus methods are recommended to throw at least `GLib.Error' or `GLib.DBusError, GLib.IOError'
    public abstract void hibernate (bool interactive) throws IOError;
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
/home/ryanr/fork-launchy/src/synapse-plugins/system-managment.vala:59.5-59.34: warning: DBus methods are recommended to throw at least `GLib.Error' or `GLib.DBusError, GLib.IOError'
    public abstract void power_off (bool interactive) throws IOError;
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
/home/ryanr/fork-launchy/src/synapse-plugins/system-managment.vala:60.5-60.38: warning: DBus methods are recommended to throw at least `GLib.Error' or `GLib.DBusError, GLib.IOError'
    public abstract string can_suspend () throws IOError;
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
/home/ryanr/fork-launchy/src/synapse-plugins/system-managment.vala:61.5-61.40: warning: DBus methods are recommended to throw at least `GLib.Error' or `GLib.DBusError, GLib.IOError'
    public abstract string can_hibernate () throws IOError;
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
/home/ryanr/fork-launchy/src/synapse-plugins/system-managment.vala:62.5-62.37: warning: DBus methods are recommended to throw at least `GLib.Error' or `GLib.DBusError, GLib.IOError'
    public abstract string can_reboot () throws IOError;
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
/home/ryanr/fork-launchy/src/synapse-plugins/system-managment.vala:63.5-63.40: warning: DBus methods are recommended to throw at least `GLib.Error' or `GLib.DBusError, GLib.IOError'
    public abstract string can_power_off () throws IOError;
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
/home/ryanr/fork-launchy/src/synapse-plugins/system-managment.vala:44.5-44.32: warning: DBus methods are recommended to throw at least `GLib.Error' or `GLib.DBusError, GLib.IOError'
    public abstract void restart () throws IOError;
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
/home/ryanr/fork-launchy/src/synapse-plugins/system-managment.vala:45.5-45.29: warning: DBus methods are recommended to throw at least `GLib.Error' or `GLib.DBusError, GLib.IOError'
    public abstract void stop () throws IOError;
    ^^^^^^^^^^^^^^^^^^^^^^^^^
/home/ryanr/fork-launchy/src/synapse-plugins/system-managment.vala:46.5-46.42: warning: DBus methods are recommended to throw at least `GLib.Error' or `GLib.DBusError, GLib.IOError'
    public abstract async bool can_restart () throws IOError;
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
/home/ryanr/fork-launchy/src/synapse-plugins/system-managment.vala:47.5-47.39: warning: DBus methods are recommended to throw at least `GLib.Error' or `GLib.DBusError, GLib.IOError'
    public abstract async bool can_stop () throws IOError;
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
/home/ryanr/fork-launchy/src/synapse-plugins/system-managment.vala:30.5-30.40: warning: DBus methods are recommended to throw at least `GLib.Error' or `GLib.DBusError, GLib.IOError'
    public abstract async void hibernate () throws IOError;
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
/home/ryanr/fork-launchy/src/synapse-plugins/system-managment.vala:31.5-31.38: warning: DBus methods are recommended to throw at least `GLib.Error' or `GLib.DBusError, GLib.IOError'
    public abstract async void suspend () throws IOError;
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
/home/ryanr/fork-launchy/src/synapse-plugins/system-managment.vala:32.5-32.48: warning: DBus methods are recommended to throw at least `GLib.Error' or `GLib.DBusError, GLib.IOError'
    public abstract async bool hibernate_allowed () throws IOError;
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
/home/ryanr/fork-launchy/src/synapse-plugins/system-managment.vala:33.5-33.46: warning: DBus methods are recommended to throw at least `GLib.Error' or `GLib.DBusError, GLib.IOError'
    public abstract async bool suspend_allowed () throws IOError;
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
/home/ryanr/fork-launchy/src/synapse-plugins/system-managment.vala:35.5-35.45: warning: DBus methods are recommended to throw at least `GLib.Error' or `GLib.DBusError, GLib.IOError'
    public abstract async void about_to_sleep () throws IOError;
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
/home/ryanr/fork-launchy/src/LaunchyView.vala:423.27-423.52: warning: `Gdk.Display.get_device_manager' has been deprecated since 3.20.
/home/ryanr/fork-launchy/src/LaunchyView.vala:423.27-423.74: warning: `Gdk.DeviceManager.get_client_pointer' has been deprecated since 3.20
/home/ryanr/fork-launchy/src/LaunchyView.vala:429.35-429.47: warning: `Gdk.Device.grab' has been deprecated since 3.20.
/home/ryanr/fork-launchy/src/LaunchyView.vala:434.34-434.45: warning: `Gdk.Device.grab' has been deprecated since 3.20.
/home/ryanr/fork-launchy/src/Widgets/AppEntry.vala:311.18-311.28: error: The name `desktop_uri' does not exist in the context of `Launcher.Widgets.AppEntry.remove_saved_item'
    string uri = desktop_uri;
                 ^^^^^^^^^^^
/home/ryanr/fork-launchy/src/Widgets/AppEntry.vala:264.18-264.28: error: The name `desktop_uri' does not exist in the context of `Launcher.Widgets.AppEntry.add_saved_item'
    string uri = desktop_uri;
                 ^^^^^^^^^^^
/home/ryanr/fork-launchy/src/Widgets/AppEntry.vala:114.17-114.26: warning: `Gtk.Menu.popup' has been deprecated since 3.22
/home/ryanr/fork-launchy/src/Widgets/SearchView.vala:104.13-104.29: warning: `Gtk.ScrolledWindow.add_with_viewport' has been deprecated since 3.8
/home/ryanr/fork-launchy/src/LaunchyView.vala:234.31-234.56: warning: `Gdk.Screen.get_primary_monitor' has been deprecated since 3.22
/home/ryanr/fork-launchy/src/LaunchyView.vala:236.13-236.39: warning: `Gdk.Screen.get_monitor_geometry' has been deprecated since 3.22
/home/ryanr/fork-launchy/src/LaunchyView.vala:291.31-291.56: warning: `Gdk.Screen.get_primary_monitor' has been deprecated since 3.22
/home/ryanr/fork-launchy/src/LaunchyView.vala:293.13-293.39: warning: `Gdk.Screen.get_monitor_geometry' has been deprecated since 3.22
/home/ryanr/fork-launchy/src/LaunchyView.vala:451.27-451.71: warning: `Gdk.Display.get_device_manager' has been deprecated since 3.20.
/home/ryanr/fork-launchy/src/LaunchyView.vala:451.27-451.93: warning: `Gdk.DeviceManager.get_client_pointer' has been deprecated since 3.20
/home/ryanr/fork-launchy/src/Launchy.vala:144.5-144.22: warning: DBus methods are recommended to throw at least `GLib.Error' or `GLib.DBusError, GLib.IOError'
    public int do_ping(int v) {
    ^^^^^^^^^^^^^^^^^^
/home/ryanr/fork-launchy/src/Launchy.vala:148.5-148.23: warning: DBus methods are recommended to throw at least `GLib.Error' or `GLib.DBusError, GLib.IOError'
    public void do_show() {
    ^^^^^^^^^^^^^^^^^^^
Compilation failed: 2 error(s), 38 warning(s)
src/CMakeFiles/panther_launcher.dir/build.make:200: recipe for target 'src/panther_launcher_valac.stamp' failed
make[2]: *** [src/panther_launcher_valac.stamp] Error 1
CMakeFiles/Makefile2:157: recipe for target 'src/CMakeFiles/panther_launcher.dir/all' failed
make[1]: *** [src/CMakeFiles/panther_launcher.dir/all] Error 2
Makefile:140: recipe for target 'all' failed
make: *** [all] Error 2

### CODE REVIEW

**Comment by nick92** [comment]
This isn't required as it's now using meson as the build tool, I've updated the files and README accordingly

**Comment by rbreaves** [comment]
Can't seem to get it to install still.

```
ryanr@ryanr-VirtualBox:~/Documents/git-projects/launchy/build$ sudo make install
make: *** No rule to make target 'install'.  Stop.
```

Closer.. I can taste it lol.

**Comment by rbreaves** [comment]
I think sudo make install should be sudo ninja install. Something is still off with it though and it is breaking in my Ubuntu Mate 20.04 test VM.

The dconf schema is not installing, I guess I could dump them from your Enso distro, not really sure where to go in your code right off to fix it in terms of it not installing.

Guessing something needs updating in this file though.

./meson/post_install.py
```
#!/usr/bin/env python3

import os
import subprocess

prefix = os.environ.get('MESON_INSTALL_PREFIX', '/usr')
datadir = os.path.join(prefix, 'share')

# Packaging tools define DESTDIR and this isn't needed for them
if 'DESTDIR' not in os.environ:
        print('Compiling gsettings schemas...')
        subprocess.call(['glib-compile-schemas', os.path.join(datadir, 'glib-2.0', 'schemas')])

        print('Updating icon cache...')
        subprocess.call(['gtk-update-icon-cache', '-qtf', os.path.join(datadir, 'icons', 'hicolor')])

        print('Updating desktop database...')
        subprocess.call(['update-desktop-database', '-q', os.path.join(datadir, 'applications')])
```

```
ryanr@ryanr-VirtualBox:~/Documents/git-projects/launchy/build$ sudo ninja install
[0/1] Installing files.
Installing lib/synapse-core/libsynapse-core.a to /usr/lib/x86_64-linux-gnu
Installing lib/synapse-plugins/libsynapse-plugins.a to /usr/lib/x86_64-linux-gnu
Installing src/launchy to /usr/bin
Installing /home/ryanr/Documents/git-projects/launchy/data/icons.gresource.xml to /usr/share/glib-2.0/schemas
Installing /home/ryanr/Documents/git-projects/launchy/data/launchy.desktop to /usr/share/applications
Running custom install script '/usr/bin/python3 /home/ryanr/Documents/git-projects/launchy/meson/post_install.py'
Compiling gsettings schemas...
Updating icon cache...
Updating desktop database...
ryanr@ryanr-VirtualBox:~/Documents/git-projects/launchy/build$ ./src/launchy

(launchy:119340): GLib-GIO-ERROR **: 15:30:32.857: Settings schema 'org.enso.launchy' is not installed
Trace/breakpoint trap (core dumped)
ryanr@ryanr-VirtualBox:~/Documents/git-projects/launchy/build$ launchy

(launchy:119823): GLib-GIO-ERROR **: 15:30:41.587: Settings schema 'org.enso.launchy' is not installed
Trace/breakpoint trap (core dumped)
ryanr@ryanr-VirtualBox:~/Documents/git-projects/launchy/build$ /usr/bin/launchy

(launchy:120981): GLib-GIO-ERROR **: 15:31:01.564: Settings schema 'org.enso.launchy' is not installed
Trace/breakpoint trap (core dumped)

```

**Comment by rbreaves** [comment]
Got it to run, ~but there are some graphical glitches. I will create a separate ticket.~

I see that the app just doesn't support dark themes atm, that's ok, I understand this is for Enso and I may need to do some customization to get it to work in the the environments I would like it in. Thanks for the awesome work!!

```
sudo cp '/home/ryanr/Documents/git-projects/launchy/data/org.enso.launchy.gschema.xml' /usr/share/glib-2.0/schemas/org.enso.launchy.gschema.xml
sudo glib-compile-schemas /usr/share/glib-2.0/schemas/
```

~Nevermind, don't see that you're accepting trouble tickets on this repo. I do have a pic I can share though. I don't mind working through it, but any advice would be appreciated.~

VirtualBox_Ubuntu Mate Degreen_25_05_2020_15_50_22
VirtualBox_Ubuntu Mate Degreen_25_05_2020_15_53_30

**Pull request closed without merging**
